version: "3"

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://localhost:27018/ideasCompartidas?retryWrites=true&w=majority
      - APPLICATION_NAME=Share Your Idea
      - JWT_SECRET=myStrongSecret
      - CACHE_KEY=myStrongPassword
      - SWAGGER_DOC=swaggerPROD
    ports:
      - "5000:5000" 
  mongo:
    image: mongo
