openapi: "3.0.0"
info:
  title: "API de Ejemplo"
  version: "1.0.0"
paths:
  /ejemplo:
    get:
      summary: "Ejemplo de ruta"
      responses:
        200:
          description: "Respuesta exitosa"
